name: 'Auto Post'

on:
  schedule:
    - cron: '0 7 * 4-10 5'       # utc+2 during german summer time
    - cron: '0 8 * 11-12,1-3 5'  # utc+1 during german winter time
  # push:
  #   branches:
  #     - 'master'

jobs:
  autopost:
    name: 'Auto Post'
    runs-on: 'ubuntu-20.04'
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Post tweet
        env:
          TWITTER_CONSUMERKEY: ${{ secrets.TWITTER_CONSUMERKEY }}
          TWITTER_CONSUMERSECRET: ${{ secrets.TWITTER_CONSUMERSECRET }}
          TWITTER_ACCESSTOKENKEY: ${{ secrets.TWITTER_ACCESSTOKENKEY }}
          TWITTER_ACCESSTOKENSECRET: ${{ secrets.TWITTER_ACCESSTOKENSECRET }}
        run: python3 itsfriday/main.py --once --config config/actions.json
