name: Extract Image
on:
  issue_comment:
    types:
      - "created"

jobs:
  extract:
    name: Extract Image
    runs-on: ubuntu-latest
    if: |-
      ${{ 
        github.event.sender.id == github.event.repository.owner.id 
        && contains(toJSON(github.event.issue.labels), 'contribute-image') 
        && github.event.comment.body == 'accept'
      }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Extract
        env:
          CONTENT: ${{ github.event.issue.body }}
          AUTHOR_LOGIN: ${{ github.event.issue.user.login }}
        run: |
          image_url=$(python3 scripts/extract-image-url.py $CONTENT)
          extension=$(python3 scripts/get-extension.py $image_url)
          uid=$(date +%s%N)
          file_name=${AUTHOR_LOGIN}_${uid}.${extension}
          curl -Lo data/pool/$file_name $image_url

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: contribute image
          branch: master